// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDAfB4Zx3DnyDOLjlXtPRN6KV-sHRZaoE',
    appId: '1:323916982451:web:54ca2d3c73822f1c18a8c6',
    messagingSenderId: '323916982451',
    projectId: 'unibus-19027',
    authDomain: 'unibus-19027.firebaseapp.com',
    storageBucket: 'unibus-19027.appspot.com',
    measurementId: 'G-5B2JCNE26Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvYQ8POIgtqaCX4H1fYHO8L4lwaeV2oQ',
    appId: '1:323916982451:android:488dab76fbff58d618a8c6',
    messagingSenderId: '323916982451',
    projectId: 'unibus-19027',
    storageBucket: 'unibus-19027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgxIt8NQTj0gEygRS3n14AWLFUpV3qgsg',
    appId: '1:323916982451:ios:e04adf14ad0d0d6f18a8c6',
    messagingSenderId: '323916982451',
    projectId: 'unibus-19027',
    storageBucket: 'unibus-19027.appspot.com',
    iosBundleId: 'com.example.unibus',
  );
}
